// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umsyxiztgfiedtibxjeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtc3l4aXp0Z2ZpZWR0aWJ4amVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5NzcyMzksImV4cCI6MjA5MDU1MzIzOX0.BCzXCyXyU62RdJATe0fqCcPiNtjFDy2adP6SpisjYyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});